server:
  port: 8443
  ssl:
    enabled: true
    key-store: file:/etc/certs/keystore.p12
    key-store-password: ${KEYSTORE_PASSWORD:030304}
    key-store-type: PKCS12
  tomcat:
    max-http-form-post-size: -1
    max-swallow-size: -1

cloud:
  aws:
    region:
      static: ${S3_REGION:ecrregion}
    s3:
      bucket: ${S3_BUCKETNAME:ecrname}
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID:}
      secret-key: ${AWS_SECRET_ACCESS_KEY:}
      profile: ${AWS_PROFILE:everflowbucket}

spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:dbtablename}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:pw}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secretKey: ${JWT_SECRET_KEY:1234512345}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION:3600000}
    header: ${JWT_ACCESS_HEADER:Authorization}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION:3600000}
    header: ${JWT_REFRESH_HEADER:RefreshToken}

# Springdoc (Swagger UI)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    display-request-duration: true
    groups-order: ASC

gemini:
  baseurl: https://generativelanguage.googleapis.com
  model: gemini-2.0-flash

googleai:
  api:
    key: AIzaSyBhvzHlWW-_bnbnZjDcWJOkS_Dwf7uNdMk
